### ISSUE TITLE
Write copy for the e-mail

### ISSUE THREAD

**Issue by prafulfillment** [Parth-Mehrotra/DriveAI-Website#4]

**Comment by AkSho** [comment]
Dear Assemblyperson

I’m writing to voice my support for Assembly Bill A-1326, which would direct the NJ Motor Vehicle Commission (MVC) to establish a driver's license endorsement for the operation of autonomous vehicles in our state.

I believe such a law would ensure that these vehicles adhere to MVC standards governing vehicle registration, safety, inspection, insurance, etc. Once enacted, the law ultimately have a positive impact on commerce, offer more choices to consumers and result in more jobs for New Jersey residents.

I would appreciate it if you would consider moving this bill forward in the General Assembly. Many thanks.

**Comment by prafulfillment** [comment]
Dear Assemblyman Ciattarelli:

I am a constituent that lives in your district and am interested in supporting Assembly Bill A1326. There's a strong community of developers in New Jersey at Princeton, NJ working with Professor Kornhauser and at Rutgers University working with startups and major insurance companies. 

As a supporter of their efforts and a strong proponent for New Jersey's economic development through high-tech, I encourage you to support this important bill for the future of New Jersey tech. 

Let's get back to being tech innovators again!

Sincerely, 
Praful Mathur

**Comment by prafulfillment** [comment]
I mixed our two together: 

---

Dear Assemblywoman Simon:

I am a constituent that lives in your district and I am voicing my support for Assembly Bill A-1326, which would direct the NJ Motor Vehicle Commission (MVC) to establish a driver's license endorsement for the operation of autonomous vehicles in our state. 

I believe such a law would ensure that these vehicles adhere to MVC standards governing vehicle registration, safety, inspection, and insurance. Once enacted, the law ultimately have a positive impact on commerce, offer more choices to consumers and result in more jobs for New Jersey residents. There is a strong community of developers in New Jersey working on the technical challenges at Princeton University, Rutgers University, Munich Re Insurance, DriveAI.com, and derivatived.com

As a supporter of their efforts and a strong proponent for New Jersey's economic development through high-tech, I encourage you to support this important bill for the future of New Jersey tech.

Let's get back to being tech innovators again!

Sincerely,
Praful Mathur

**Comment by AkSho** [comment]
This is good. We can move forward with this.

**Comment by prafulfillment** [comment]
Closed by b18358fb6a35501bb50ba616f4c9a9607bba1e9b
